### ISSUE TITLE
No Project Closed Issue |||||||| ~!@#$%%%^&*()_+<>?"""'''''

### ISSUE THREAD

**Issue by 1test-migration** [1test-migration/public_project_test#5]
### Class Guides | Players
The DnD 5e Wizard Guide
**Published on March 5, 2020, Last modified on April 3rd, 2021**
_In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook._

> 5e Wizard fighting an giant floating monster with tentacles

- What is this guide?
- This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

1. Red isn’t going to contribute to the effectiveness of your character build at all
2. Orange is an OK option
3. Green is a good option
4. Blue is a great option, you should strongly consider this option for your character
5. Sky Blue is an amazing option. If you do not take this option your character would not be optimized
6. So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

- [ ] 
Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

Class Guides | Players
The DnD 5e Wizard Guide
Published on March 5, 2020, Last modified on April 3rd, 2021
In this post, we will be examining the Wizard’s Class Features and how you can optimize your Wizard through choosing your Race, Ability Score, Spells, Feats, etc. This article will focus primarily on content from the Dungeon Master’s Guide and Player’s Handbook.

5e Wizard fighting an giant floating monster with tentacles
What is this guide?
This guide is meant as a deep dive into the DnD 5e Wizard. For a quick overview on the Wizard Class, see our breakdown of the DnD 5e Classes. You can see the Wizard Class Features here.

The color code below has been implemented to help you identify, at a glance, how good that option will be for your Wizard. This color coding isn’t a hard and fast rule; there are plenty of sub-optimized options out there that will be viable to your party and will be fun to play.

Red isn’t going to contribute to the effectiveness of your character build at all
Orange is an OK option
Green is a good option
Blue is a great option, you should strongly consider this option for your character
Sky Blue is an amazing option. If you do not take this option your character would not be optimized
So if you’re ready, grab your spellbook and cast Fireball until all of your problems go away.

**Translate block**

German
Diese Anleitung ist als tiefer Einblick in den DnD 5e-Assistenten gedacht. Eine schnelle Übersicht über die Assistentenklasse finden Sie in unserer Aufschlüsselung der DnD 5e-Klassen. Sie können die Assistentenklassenfunktionen hier sehen. Der folgende Farbcode wurde implementiert, damit Sie auf einen Blick erkennen können, wie gut diese Option für Ihren Assistenten ist. Diese Farbcodierung ist keine feste Regel. Es gibt viele suboptimierte Optionen, die für Ihre Party geeignet sind und Spaß machen.

French
Ce guide se veut une plongée approfondie dans l'assistant DnD 5e. Pour un aperçu rapide de la classe Wizard, consultez notre répartition des classes DnD 5e. Vous pouvez voir les fonctionnalités de la classe Wizard ici. Le code couleur ci-dessous a été implémenté pour vous aider à identifier, en un coup d'œil, à quel point cette option sera bonne pour votre assistant. Ce code couleur n’est pas une règle absolue; il existe de nombreuses options sous-optimisées qui seront viables pour votre groupe et seront amusantes à jouer.

Portuguese
Este guia pretende ser um mergulho profundo no DnD 5e Wizard. Para uma rápida visão geral da classe Wizard, veja nosso detalhamento das classes DnD 5e. Você pode ver os recursos da classe Wizard aqui. O código de cores abaixo foi implementado para ajudá-lo a identificar, de relance, o quão boa essa opção será para o seu assistente. Este código de cores não é uma regra rígida e rápida; existem muitas opções subotimizadas que serão viáveis ​​para o seu grupo e divertidas de jogar.

Spanish
Esta guía está pensada como una inmersión profunda en el asistente DnD 5e. Para obtener una descripción general rápida de la clase Wizard, consulte nuestro desglose de las clases DnD 5e. Puede ver las características de la clase del asistente aquí. El siguiente código de color se ha implementado para ayudarlo a identificar, de un vistazo, qué tan buena será esa opción para su asistente. Esta codificación de colores no es una regla estricta; Hay muchas opciones sub-optimizadas que serán viables para tu grupo y serán divertidas de jugar.
![gif](https://user-images.githubusercontent.com/84837906/119645518-c77fac80-be26-11eb-9539-49d0e6eaccf5.gif)
![jpeg2@1x](https://user-images.githubusercontent.com/84837906/119645520-c8184300-be26-11eb-8d1f-df382ddc4a08.jpg)
![png@1x](https://user-images.githubusercontent.com/84837906/119645526-c8b0d980-be26-11eb-9e66-a10ef2aa377c.png)

**Comment by 1test-migration** [comment]
Test comment|!

**Comment by 1test-migration** [comment]
>

**Comment by 1test-migration** [comment]
-

**Comment by 1test-migration** [comment]
succeed as a wizard, improving your familiarity with the game will pay dividends.

After reading this handbook, I encourage you to read my Wizard Subclasses Breakdown and my Wizard Spells Breakdown.

Wizard Class Features
Optional Class Features are detailed below under Optional Class Features.

Hit Points: d6 hit points is the lowest in the game. Fortunately Intelligence is the only ability which Wizards strictly need, so you can afford a decent Constitution score.

Saves: Intelligence saves are very rare, and proficiency in Wisdom saves won't help much if your Wisdom is terrible.

Proficiencies: Wizard's weapons are pitiful, but can be easily replaced by cantrips. Wizards also get no armor, so it's either Mage Armor or nothing for the vast majority of wizards. Wizards only get the standard two skills, which is difficult considering that your party will expect you to cover as many knowledge skills as possible, leaving many wizards with little room to diversify.

**Comment by 1test-migration** [comment]
@Migration-comment

**Comment by Migration-comment** [comment]
Arcane Tradition: Wizard subclasses are briefly summarized below. See my Wizard Subclasses Breakdown for help selecting your subclass.

Bladesinging: Elven masters of fighting with both weapons and with spells, bladesingers can perform a secret song and dance which makes them deadly
Chronurgy Magic: Manipulate the flow of time, allowing you to force rerolls, to stop creatures, and even to temporarily suspend spells in a tiny bead and share it with your allies. Chronurgists also gain access to the Dunamancy spell list.
Graviturgy Magic: Manipulate space and gravity to move your foes about on the battlefield and crush them with powerful gravitational effects. Graviturgists also gain access to the Dunamancy spell list.
Order of the Scribes: Awaken your spellbook, and master the central concepts of wizardly magic, allowing you to learn spells faster than other wizards and employ them in new and unusual ways.
School of Abjuration: Masters of protective magic, Abjurers gain a powerful magical ward which can absorb damage dealt to you or your allies and recharges when you cast abjuration spells.
School of Conjuration: Masters of teleportation and summoning, conjurers can teleport without using a spell and are better at using summoned creatures.
School of Divination: Diviners gain the powerful Portent feature, allowing them to roll two to three d20's at the beginning of the day and use them to replace rolls, as well as the ability to cast divination spells and incredible little cost.
School of Enchantment: Powerful and versatile spellcasters, enchanters gain abilities to charm and hypnotize foes, and to affect additional targets with single-target enchantment spells.
School of Evocation: Exceptional at dealing damage with spells, evokers deal more damage with cantrips than other spellcaster, and can make safe spaces in their area damage spells to avoid harming allies.
School of Illusion: Masters of illussion spells, illusionists gain abilities to manipulate illusion spells beyond their normal limits, including the ability to make them partially real.
School of Necromancy: Gain the ability to heal yourself when you kill other creatures, and to more easily create and control undead, including powerful ones far more powerful than spells alone would allow.
School of Transmutation: Gain abilities to turn things into other things, like wood into metal, yourself into an animal, dead things into live things, and injured or sick things into happy and healthy things.
War Magic: Powerful combatants, war wizards gain abilities to defend themselves against attacks and to boost their spell damage by countering or dispelling other spells.

**Comment by Migration-comment** [comment]
1

**Comment by Migration-comment** [comment]
2

**Comment by Migration-comment** [comment]
3

**Comment by Migration-comment** [comment]
4

**Comment by Migration-comment** [comment]
5

**Comment by Migration-comment** [comment]
6

**Comment by Migration-comment** [comment]
7

**Comment by Migration-comment** [comment]
8

**Comment by Migration-comment** [comment]
9

**Comment by Migration-comment** [comment]
10

**Comment by Migration-comment** [comment]
11

**Comment by Migration-comment** [comment]
12

**Comment by Migration-comment** [comment]
13

**Comment by Migration-comment** [comment]
14

**Comment by Migration-comment** [comment]
15

**Comment by Migration-comment** [comment]
16

**Comment by Migration-comment** [comment]
17

**Comment by Migration-comment** [comment]
18

**Comment by Migration-comment** [comment]
19

**Comment by Migration-comment** [comment]
20
21

**Comment by 1test-migration** [comment]
+
